# Generated by Django 2.2.3 on 2019-07-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='servico',
            new_name='servicos',
        ),
    ]
