# Generated by Django 2.2.3 on 2019-07-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_auto_20190728_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('Nome', models.CharField(max_length=100)),
                ('Endereço', models.CharField(max_length=50)),
                ('Bairro', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='servicos',
            name='data_execucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servico.cliente'),
            preserve_default=False,
        ),
    ]
