# Generated by Django 2.2.3 on 2019-07-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_auto_20190728_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf_cnpj',
            new_name='CPf',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cidade',
            new_name='Telefone1',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='data_criacao',
            new_name='Data_criacao',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='data_execucao',
            new_name='Data_execucao',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='descricao',
            new_name='Descricao',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='obs',
            new_name='Obs',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='valor',
            new_name='Valor',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Cidade',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='Telefone2',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Endereço',
            field=models.CharField(max_length=100),
        ),
    ]
